java_library(
    name = "math",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/java/sigprop3",
        "//src/java/sigprop3/signal/sync",
    ],
)
