# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yuca/profiler/linux/powercap/powercap.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'yuca/profiler/linux/powercap/powercap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+yuca/profiler/linux/powercap/powercap.proto\x12\x1cyuca.profiler.linux.powercap\"\xbc\x01\n\x0ePowercapEnergy\x12\x13\n\x06socket\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x13\n\x06\x65nergy\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x10\n\x03pkg\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x11\n\x04\x64ram\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x11\n\x04\x63ore\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x10\n\x03gpu\x18\x06 \x01(\x01H\x05\x88\x01\x01\x42\t\n\x07_socketB\t\n\x07_energyB\x06\n\x04_pkgB\x07\n\x05_dramB\x07\n\x05_coreB\x06\n\x04_gpuB0\n\x1cyuca.profiler.linux.powercapB\x0ePowercapProtosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yuca.profiler.linux.powercap.powercap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034yuca.profiler.linux.powercapB\016PowercapProtosP\001'
  _globals['_POWERCAPENERGY']._serialized_start=78
  _globals['_POWERCAPENERGY']._serialized_end=266
# @@protoc_insertion_point(module_scope)
