java_binary(
    name = "FakeCounter",
    main_class = "sigprop.examples.FakeCounter",
    srcs = ["FakeCounter.java"],
    deps = [
        "//src/java/sigprop",
        "//src/java/sigprop/signal",
        "//src/java/sigprop/signal/async",
        "//src/java/sigprop/signal/sync",
        "//src/java/sigprop/signal/util",
        "//src/java/sigprop/util",
    ]
)

java_binary(
    name = "SigpropExample",
    main_class = "sigprop.examples.SigpropExample",
    srcs = ["SigpropExample.java"],
    deps = [
        "//src/java/sigprop2",
        "//src/java/sigprop2/signal",
        "//src/java/sigprop2/signal/concurrent",
        "//src/java/sigprop2/util",
    ]
)

java_binary(
    name = "FakeTaskActivity",
    main_class = "sigprop.examples.FakeTaskActivity",
    srcs = ["FakeTaskActivity.java"],
    deps = [
        "//src/java/sigprop2",
        "//src/java/sigprop2/signal",
        "//src/java/sigprop2/signal/concurrent",
        "//src/java/sigprop2/util",
    ]
)
