java_binary(
    name = "Timer",
    srcs = ["Timer.java"],
    main_class = "sigprop.examples.Timer",
    deps = [
        "//src/java/sigprop",
        "//src/java/sigprop/signal",
        "//src/java/sigprop/signal/util",
    ],
)

java_binary(
    name = "MuonTomography",
    srcs = ["MuonTomography.java"],
    main_class = "sigprop.examples.MuonTomography",
    deps = [
        "//src/java/sigprop",
        "//src/java/sigprop/signal",
        "//src/java/sigprop/signal/math/scalar",
        "//src/java/sigprop/signal/util",
    ],
)
