java_binary(
    name = "MuonTomography",
    main_class = "sigprop3.examples.MuonTomography",
    srcs = ["MuonTomography.java"],
    deps = [
        "//src/java/sigprop3",
        "//src/java/sigprop3/signal/concurrent",
        "//src/java/sigprop3/signal/math/scalar",
        "//src/java/sigprop3/signal/sync",
        "//src/java/sigprop3/signal/util",
    ]
)
