[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yuca"
version = "0.1.0"
dependencies = [
    "grpcio",
    "protobuf",
    "tqdm",
    "pandas",
    "matplotlib",
]

[tool.setuptools.packages.find]
where = ["profiler/python"]
