java_library(
    name = "scalar",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/java/charcoal",
        "//src/java/charcoal/prop",
        "//src/java/charcoal/prop/math",
    ],
)
