java_library(
    name = "util",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//profiler/java/yuca/profiler",
        "//profiler/java/yuca/profiler/emissions",
    ]
)
