java_library(
    name = "async",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/java/sigprop",
        "//src/java/sigprop/signal",
        "//src/java/sigprop/util",
    ],
)
