java_library(
    name = "jiffies",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//profiler/java/charcoal/profiler/linux",
        "//profiler/java/charcoal/profiler/linux/powercap",
        "//profiler/proto/charcoal/profiler/linux:linux_java_protos",
        "//profiler/proto/charcoal/profiler/linux/jiffies:jiffies_java_protos",
        "//profiler/proto/charcoal/profiler/linux/powercap:powercap_java_protos",
        "//src/java/charcoal",
        "//src/java/charcoal/prop",
        "//src/java/charcoal/util",
    ],
)
