java_library(
    name = "scalar",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/java/sigprop",
        "//src/java/sigprop/signal",
        "//src/java/sigprop/signal/math",
    ],
)
