# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yuca/profiler/linux/jiffies/jiffies.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'yuca/profiler/linux/jiffies/jiffies.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yuca.profiler.linux import linux_pb2 as yuca_dot_profiler_dot_linux_dot_linux__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)yuca/profiler/linux/jiffies/jiffies.proto\x12\x1byuca.profiler.linux.jiffies\x1a\x1fyuca/profiler/linux/linux.proto\"\xdc\x01\n\x0bTaskJiffies\x12,\n\x04task\x18\x01 \x01(\x0b\x32\x19.yuca.profiler.linux.TaskH\x00\x88\x01\x01\x12\x10\n\x03\x63pu\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x14\n\x07jiffies\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x19\n\x0cuser_jiffies\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x1b\n\x0esystem_jiffies\x18\x05 \x01(\rH\x04\x88\x01\x01\x42\x07\n\x05_taskB\x06\n\x04_cpuB\n\n\x08_jiffiesB\x0f\n\r_user_jiffiesB\x11\n\x0f_system_jiffies\"~\n\x0fTaskJiffiesRate\x12,\n\x04task\x18\x01 \x01(\x0b\x32\x19.yuca.profiler.linux.TaskH\x00\x88\x01\x01\x12\x10\n\x03\x63pu\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x11\n\x04rate\x18\x03 \x01(\x01H\x02\x88\x01\x01\x42\x07\n\x05_taskB\x06\n\x04_cpuB\x07\n\x05_rate\"\xfc\x02\n\nCpuJiffies\x12\x10\n\x03\x63pu\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x14\n\x07jiffies\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x11\n\x04user\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x11\n\x04nice\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x13\n\x06system\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12\x11\n\x04idle\x18\x06 \x01(\x04H\x05\x88\x01\x01\x12\x13\n\x06iowait\x18\x07 \x01(\x04H\x06\x88\x01\x01\x12\x10\n\x03irq\x18\x08 \x01(\x04H\x07\x88\x01\x01\x12\x14\n\x07softirq\x18\t \x01(\x04H\x08\x88\x01\x01\x12\x12\n\x05steal\x18\n \x01(\x04H\t\x88\x01\x01\x12\x12\n\x05guest\x18\x0b \x01(\x04H\n\x88\x01\x01\x12\x17\n\nguest_nice\x18\x0c \x01(\x04H\x0b\x88\x01\x01\x42\x06\n\x04_cpuB\n\n\x08_jiffiesB\x07\n\x05_userB\x07\n\x05_niceB\t\n\x07_systemB\x07\n\x05_idleB\t\n\x07_iowaitB\x06\n\x04_irqB\n\n\x08_softirqB\x08\n\x06_stealB\x08\n\x06_guestB\r\n\x0b_guest_nice\"F\n\x0e\x43puJiffiesRate\x12\x10\n\x03\x63pu\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04rate\x18\x02 \x01(\x01H\x01\x88\x01\x01\x42\x06\n\x04_cpuB\x07\n\x05_rateB.\n\x1byuca.profiler.linux.jiffiesB\rJiffiesProtosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yuca.profiler.linux.jiffies.jiffies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033yuca.profiler.linux.jiffiesB\rJiffiesProtosP\001'
  _globals['_TASKJIFFIES']._serialized_start=108
  _globals['_TASKJIFFIES']._serialized_end=328
  _globals['_TASKJIFFIESRATE']._serialized_start=330
  _globals['_TASKJIFFIESRATE']._serialized_end=456
  _globals['_CPUJIFFIES']._serialized_start=459
  _globals['_CPUJIFFIES']._serialized_end=839
  _globals['_CPUJIFFIESRATE']._serialized_start=841
  _globals['_CPUJIFFIESRATE']._serialized_end=911
# @@protoc_insertion_point(module_scope)
