java_library(
    name = "linux",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//profiler/java/charcoal/profiler/emissions",
        "//profiler/proto/charcoal/profiler/linux:linux_java_protos",
        "//src/java/charcoal",
        "//src/java/charcoal/prop",
        "//src/java/charcoal/util",
    ],
)
