java_library(
    name = "meminfo",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//profiler/java/yuca/profiler/linux",
        "//profiler/java/yuca/profiler/linux/powercap",
        "//profiler/proto/yuca/profiler/linux:linux_java_protos",
        "//src/java/charcoal",
        "//src/java/charcoal/prop",
        "//src/java/charcoal/util",
    ],
)
