java_binary(
    name = "Timer",
    srcs = ["Timer.java"],
    main_class = "charcoal.examples.Timer",
    deps = [
        "//src/java/charcoal",
        "//src/java/charcoal/prop",
        "//src/java/charcoal/prop/math/scalar",
        "//src/java/charcoal/prop/util",
        "//src/java/charcoal/util",
    ],
)

java_binary(
    name = "MuonTomography",
    srcs = ["MuonTomography.java"],
    main_class = "charcoal.examples.MuonTomography",
    deps = [
        "//src/java/charcoal",
        "//src/java/charcoal/prop",
        "//src/java/charcoal/prop/math/scalar",
        "//src/java/charcoal/prop/util",
    ],
)
