java_library(
    name = "profiler",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//profiler/java/charcoal/profiler/linux",
        "//profiler/java/charcoal/profiler/emissions",
        "//profiler/java/charcoal/profiler/linux/freq",
        "//profiler/java/charcoal/profiler/linux/jiffies",
        "//profiler/java/charcoal/profiler/linux/powercap",
        "//src/java/charcoal/prop",
        "//src/java/charcoal/util",
    ]
)
